export enum GoalStatus {
    NOT_STARTED = 'NOT_STARTED',
    IN_PROGRESS = 'IN_PROGRESS',
    ON_TRACK = 'ON_TRACK',
    FALLING_BEHIND = 'FALLING_BEHIND',
    ACHIEVED = 'ACHIEVED',
    ABANDONED = 'ABANDONED'
}
